#ifndef UART_PLATFORM_SPECIFIC
#define UART_PLATFORM_SPECIFIC

#include "error_handling.h"
#include "clock_system/peripheral_clocking.h"
#include "irq/sercom_stuff.h"
#include <stdio.h>

typedef enum {
    UART_PERIPHERAL_0,
    UART_PERIPHERAL_1,
    UART_PERIPHERAL_2,
    UART_PERIPHERAL_3,
    UART_PERIPHERAL_4,
    UART_PERIPHERAL_5,
} uart_peripheral_inst_t;

typedef enum {
    UART_EXTRA_OPT_USE_DEFAULT,
    UART_EXTRA_OPT_LSB_FIRST = 1073741824,
    UART_EXTRA_OPT_FALLING_TXD_RISING_RXD = 536870912,
    UART_EXTRA_OPT_SYNCHRONOUS_COMMUNICATION = 268435456,
    UART_EXTRA_OPT_AUTO_BAUD  = 83886080,
    UART_EXTRA_OPT_PARITY = 16777216,
    UART_EXTRA_OPT_RX_PAD_1 = 1048576,
    UART_EXTRA_OPT_RX_PAD_2 = 2097152,
    UART_EXTRA_OPT_RX_PAD_3 = 3145728,
    UART_EXTRA_OPT_TX_PAD_1 = 65536,
    UART_EXTRA_OPT_TX_PAD_2 = 131072,
    UART_EXTRA_OPT_OVERSAMPL_3X_ARITH = 1024,
    UART_EXTRA_OPT_OVERSAMPL_8X_FRACT = 768,
    UART_EXTRA_OPT_OVERSAMPL_8X_ARITH = 512,
    UART_EXTRA_OPT_OVERSAMPL_16X_FRACT = 256,
    UART_EXTRA_OPT_INTERNAL_CLOCK = 128,
    UART_EXTRA_OPT_ENABLE_RX = 64,
    UART_EXTRA_OPT_IRDA_ENCODING = 32,
    UART_EXTRA_OPT_COLLISION_DETECT = 16,
    UART_EXTRA_OPT_TWO_STOP_BITS = 8,
    UART_EXTRA_OPT_CHAR_SIZE_5_BITS = 5,
    UART_EXTRA_OPT_CHAR_SIZE_6_BITS = 6,
    UART_EXTRA_OPT_CHAR_SIZE_7_BITS = 7,
    UART_EXTRA_OPT_CHAR_SIZE_9_BITS = 1,
} uart_extra_config_opt_t;

typedef enum {
    UART_CLK_SOURCE_USE_DEFAULT = 0x00,
    UART_CLK_SOURCE_FAST_CLKGEN0 = 0x01,
    UART_CLK_SOURCE_FAST_CLKGEN1 = 0x02,
    UART_CLK_SOURCE_FAST_CLKGEN2 = 0x03,
    UART_CLK_SOURCE_FAST_CLKGEN3 = 0x04,
    UART_CLK_SOURCE_FAST_CLKGEN4 = 0x05,
    UART_CLK_SOURCE_FAST_CLKGEN5 = 0x06,
    UART_CLK_SOURCE_FAST_CLKGEN6 = 0x07,
    UART_CLK_SOURCE_FAST_CLKGEN7 = 0x08,
    UART_CLK_SOURCE_SLOW_CLKGEN0 = 0x100,
    UART_CLK_SOURCE_SLOW_CLKGEN1 = 0x200,
    UART_CLK_SOURCE_SLOW_CLKGEN2 = 0x300,
    UART_CLK_SOURCE_SLOW_CLKGEN3 = 0x400,
    UART_CLK_SOURCE_SLOW_CLKGEN4 = 0x500,
    UART_CLK_SOURCE_SLOW_CLKGEN5 = 0x600,
    UART_CLK_SOURCE_SLOW_CLKGEN6 = 0x700,
    UART_CLK_SOURCE_SLOW_CLKGEN7 = 0x800,
} uart_clock_sources_t;

#endif /* UART_PLATFORM_SPECIFIC */